mysite/doctor/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

app_name = 'doctor'
urlpatterns = [
    # 统一前缀为doctor
    # 这部分是诊断页面的，要修改index
    url(r'^entry', views.entry_index, name='entry'),
    url(r'^medicine_information/$', views.medicine_information, name='medicine_information'),
    url(r'^main_information/$', views.main_information, name='main_information'),
    url(r'^result/$', views.result, name='result'),
    url(r'^display/$', views.display, name='display'),
    url(r'^diagnose/$', views.diagnose, name='diagnose'),
    url(r'^diag_record/([0-9]+)/$', views.diag_record, name='diag_record'),
    # 这部分是病人资料的
    url(r'^$', views.index, name='index'),
    url(r'^patient/$', views.patient, name='patient'),
    url(r'^patient_log/$', views.patient_log, name='patient_log'),
    url(r'^patient_edit/$', views.patient_edit, name='patient_edit'),
    url(r'^patient_search/$', views.patient_search, name='patient_search'),
    url(r'^patient_search_day/$', views.patient_search_day, name='patient_search_day'),
    url(r'^patient_num/$', views.patient_num, name='patient_num'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    # 这部分挂号
    url(r'^registration/$', views.register, name='registration'),
    url(r'^r_search/$', views.r_search, name='r_search'),
    url(r'^r_display/$', views.r_display, name='r_display'),
    url(r'^r_index/$', views.r_index, name='r_index'),
    #
    url(r'^price/$', views.price, name='price'),
    # 这部分药品管理的
    url(r'^medicine/$', views.medicine, name='medicine'),
    url(r'^medicine_add/$', views.medicine_add, name='medicine_add'),
    url(r'^medicine_num/$', views.medicine_num, name='medicine_num'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^doctor/', include('doctor.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/doctor/forms.py
# -*- coding: utf-8 -*-
from django import forms
import datetime
from .models import Patient, Medicine

from django.utils.translation import ugettext_lazy as _


class MedForm(forms.ModelForm):
    class Meta:
        model = Medicine
        fields = '__all__'
        labels = {
            'name': _('药品名称'),
            'price': _('价格'),
            'number': _('编号'),
            'amount': _('余量'),
            'sort': _('分类'),
            'unit': _('单位'),
        }


class MAddForm(forms.Form):
    药品编号 = forms.IntegerField()
    增加的量 = forms.IntegerField()


class TesPForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = '__all__'
        labels = {
            'p_name': _('姓名'),
            'p_age': _('年龄'),
            'p_number': _('病人编号'),
            'p_tel_number': _('电话号码'),
            'p_sex': _('性别'),
            'p_marriage': _('婚姻状况'),
            'p_address': _('住址'),
            'p_id_num': _('身份证号码'),
        }


class EditForm(forms.Form):
    病人编号 = forms.IntegerField()


class EditToBeSaveForm(forms.Form):
    sex_choice = (
        ('男', '男'),
        ('女', '女'),
    )
    病人编号 = forms.IntegerField(label='你要修改的病人编号')
    姓名 = forms.CharField(max_length=100)
    年龄 = forms.IntegerField()
    电话号码 = forms.IntegerField()
    性别 = forms.ChoiceField(choices=sex_choice)


class LoginForm(forms.Form):
    账号 = forms.CharField(max_length=100)
    密码 = forms.CharField(max_length=100)


class AddForm(forms.Form):
    药品名称 = forms.CharField(max_length=100)
    数量 = forms.IntegerField()


class SearchForm(forms.Form):
    划价编号 = forms.IntegerField()


class DiagnoseForm(forms.Form):
    病人编号 = forms.IntegerField()
    挂号编号 = forms.IntegerField()
    诊断结果 = forms.CharField(widget=forms.Textarea)
    诊断时间 = forms.DateTimeField(initial=datetime.datetime.today())
    操作人 = forms.CharField()


class RegisterForm(forms.Form):
    挂号编号 = forms.IntegerField()
    姓名 = forms.CharField(max_length=100)
    section = (
        ('内科', '内科'),
        ('外科', '外科'),
        (None, '请选择科室')
    )
    科室 = forms.ChoiceField(
        choices=section,
    )
    费用 = forms.FloatField()
    操作人 = forms.CharField(max_length=100)


class ReSearchForm(forms.Form):
    挂号编号 = forms.IntegerField()


class MedicineAddForm(forms.Form):
    药品编号 = forms.IntegerField()
    添加数量 = forms.IntegerField()

mysite/doctor/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from .forms import *
from .models import *
from django.contrib.auth.decorators import permission_required
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
import time, datetime


login_url = "http://localhost:8000/doctor/login/"
name_dic = {
    'doctor': '孟医生',
    'dogewzy': '管理员',
    'guahao': '挂号员小李',
    'yaofang': '药房小刘',
}

# 这个还没用到
@permission_required(perm='doctor.add_price',
                     login_url=login_url)
def entry_index(request):
    # 提供查询入口
    return render(request, 'doctor/index.html')


def main_information(request):
    # 在医生填写完基本信息之后转到这个url
    # 接收基本划价信息
    # 通过hidden input传递了划价编号
    if request.method == 'POST':
        form = DiagnoseForm(request.POST)
        if form.is_valid():
            new = Diagnose()
            new.register_num = form.cleaned_data['挂号编号']
            new.p_number = form.cleaned_data['病人编号']
            new.man = form.cleaned_data['操作人']
            new.time = form.cleaned_data['诊断时间']
            new.result = form.cleaned_data['诊断结果']
            new.prescription = ''
            new.save()
            addform = AddForm()
            m = Medicine.objects.all()
            info = {}
            for i in m:
                info[i.name] = i.amount
            return render(request, 'doctor/medicine.html', {'number': new.register_num, 'addform': addform,
                                                            'info': info})


def medicine_information(request):
    # 显示药品划价信息表单,以及已经添加的药品
    # 这里有一个hidden input
    # 把所有
    if request.method == 'POST':
        form = AddForm(request.POST)
        if form.is_valid():
            number = request.POST['number']
            the_diagnose = Diagnose.objects.get(register_num=number)
            the_diagnose.prescription += form.cleaned_data['药品名称'] + '!' + str(form.cleaned_data['数量']) + '#'
            # 调整了药品余量
            the_m = Medicine.objects.get(name=form.cleaned_data['药品名称'])
            the_m.amount -= form.cleaned_data['数量']
            the_m.save()
            the_diagnose.save()
            # 提取药品信息
            all_m = the_diagnose.get_medicine_list()
            addform = AddForm()
            # 提供药品余量信息,这里比较蠢，提供了所有的
            m = Medicine.objects.all()
            info = {}
            for i in m:
                info[i.name] = i.amount
            return render(request, 'doctor/medicine.html', {'info': info, 'all_m': all_m,
                                                            'number': number, 'addform': addform})


def result(request):

    return render(request, 'doctor/result.html')


@permission_required(perm='doctor.add_price',
                     login_url=login_url)
def display(request):

    '''药房根据挂号编号开药'''

    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            num = form.cleaned_data['划价编号']
            price = Diagnose.objects.get(register_num=num)
            # 需要处理的一个额外逻辑是余量管理
            process_li = price.get_all_name_num()
            for i in process_li:
                target = Medicine.objects.get(name=i[0])
                target.amount -= int(i[1])
                target.save()
            # 展示context中需要num，p_num，total_cost,man,一个药品信息的list
            p_num = price.p_number
            man = price.man
            li = price.get_medicine_list()
            total_cost = price.get_total_price()
            return render(request, 'doctor/display.html', {
                'num': num,
                'p_num': p_num,
                'man': man,
                'li': li,
                'total_cost': total_cost,
            })

    else:
        form = SearchForm()
        return render(request, 'doctor/search.html', {'form': form})


@permission_required(perm='doctor.add_diagnose',
                     login_url=login_url)
def diagnose(request):
    form = DiagnoseForm()
    name = name_dic[request.user.username]

    return render(request, 'doctor/diagnose.html', {'form': form, 'name': name,
                                                    })


def diag_record(request, p_num):
    d = Diagnose.objects.filter(p_number=p_num)
    r = []
    for each_diagnose in d:
        r.append((each_diagnose.result, each_diagnose.prescription, each_diagnose.time))
    return render(request, 'doctor/diag_record.html', {'record': r})


def index(request):
    return render(request, 'polls/index.html')


def patient(request):
    all_patients = Patient.objects.order_by('id')
    return render(request, 'polls/patient.html', {'all_patients': all_patients})


def patient_log(request):
    is_ok = False
    print(1)
    if request.method == 'POST':
        print(2)
        form = TesPForm(request.POST)
        if form.is_valid():
            print(3)
            new_p = Patient()
            new_p.p_name = form.cleaned_data['p_name']
            new_p.p_sex = form.cleaned_data['p_sex']
            new_p.p_age = form.cleaned_data['p_age']
            new_p.p_number = form.cleaned_data['p_number']
            new_p.p_tel_number = form.cleaned_data['p_tel_number']
            new_p.p_address = form.cleaned_data['p_address']
            new_p.p_marriage = form.cleaned_data['p_marriage']
            new_p.p_id_num = form.cleaned_data['p_id_num']
            new_p.save()
            is_ok = True
            return render(request, 'polls/patient_log.html', {'form': form, 'isok': is_ok})
    else:
        form = TesPForm()
    return render(request, 'polls/patient_log.html', {'form': form, 'isok': is_ok})


def patient_num(request):
    if request.method == 'POST':
        form = EditForm(request.POST)
        if form.is_valid():
            num = form.cleaned_data['病人编号']
            new_p = Patient.objects.get(p_number=num)
            form = EditToBeSaveForm(initial={'病人编号': new_p.p_number,
                                             '姓名': new_p.p_name,
                                             '电话号码': new_p.p_tel_number,
                                             '性别': new_p.p_sex,
                                             '年龄': new_p.p_age,
                                             })
            return render(request, 'polls/patient_num.html', {'form': form})


def patient_edit(request):
    if request.method == 'POST':
        form = EditToBeSaveForm(request.POST)
        print(11)
        if form.is_valid():
            print(12)
            p = Patient.objects.get(p_number=form.cleaned_data['病人编号'])
            p.p_name = form.cleaned_data['姓名']
            p.p_sex = form.cleaned_data['性别']
            p.p_tel_number = form.cleaned_data['电话号码']
            p.p_age = form.cleaned_data['年龄']
            p.save()
            print(22)
            return render(request, 'polls/message.html')
    # 点击编辑按钮后跳到这里，在这个view中输入编号，再跳到patient_num
    else:
        form = EditForm()
        return render(request, 'polls/patient_edit.html', {'form': form})


def patient_search(request):
    if request.method == 'POST':
        form = EditForm(request.POST)
        if form.is_valid():
            number = form.cleaned_data['病人编号']
            patient_s = Patient.objects.filter(p_number=number)[0]
            return render(request, 'polls/patient_display.html', {'patient': patient_s})
    else:
        form = EditForm()
        return render(request, 'polls/patient_search.html', {'form': form})


def patient_search_day(request):
    p = Diagnose.objects.all()
    today = []
    person = []
    for i in p:
        if i.time.date() == datetime.date.today():
            today.append(i)
    for i in today:
        p = Patient.objects.get(p_number=i.p_number)
        person.append(p)
    l = len(person)
    return render(request, 'polls/patient_search_day.html', {'all_person': person,
                                                             'length': l})


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['账号']
            password = form.cleaned_data['密码']
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                print(user.user_permissions)
                return render(request, 'polls/index.html')
            else:
                pass
    else:
        form = LoginForm()
        return render(request, 'polls/login.html', {'form': form})


def logout(request):
    auth_logout(request)
    message = '您已经登出'
    return render(request, 'polls/index.html', {'message': message})


def patient_record(request, p_num):
    pass


def price(request):
    pass


@permission_required(perm='doctor.add_medicine',
                     login_url=login_url)
def medicine(request):
    all_medicine = Medicine.objects.order_by('id')
    return render(request, 'medicine/index.html', {'all_medicine': all_medicine})


def medicine_add(request):
    if request.method == 'POST':
        form = MedForm(request.POST)
        if form.is_valid():
            m = Medicine()
            m.name = form.cleaned_data['name']
            m.amount = form.cleaned_data['amount']
            m.number = form.cleaned_data['number']
            m.price = form.cleaned_data['price']
            m.sort = form.cleaned_data['sort']
            m.unit = form.cleaned_data['unit']
            m.save()
            all_medicine = Medicine.objects.order_by('id')
            return render(request, 'medicine/index.html', {'all_medicine': all_medicine})
    form = MedForm()
    return render(request, 'medicine/add.html', {'form': form})


def medicine_num(request):
    if request.method == 'POST':
        form = MAddForm(request.POST)
        if form.is_valid():
            m = Medicine.objects.get(number=form.cleaned_data['药品编号'])
            m.amount += form.cleaned_data['增加的量']
            m.save()

mysite/doctor/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.min.css' %}" />
<script src="{% static 'polls/js/bootstrap.min.js' %}"></script>
<script src="{% static 'polls/js/jquery-3.1.1.min.js' %}"></script>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'doctor:index' %}">小孟诊所</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li><a href="http://localhost:8000/admin/">系统管理</a></li>
        <li><a href="{% url 'doctor:registration' %}">挂号管理</a></li>
        <li><a href="{% url 'doctor:patient' %}">病人资料</a></li>
        <li><a href="{% url 'doctor:diagnose' %}">就诊业务</a></li>
        <li><a href="{% url 'doctor:display' %}">门诊划价</a></li>
        <li><a href="{% url 'doctor:medicine' %}">药品管理</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<li id="logout"><a href="{% url 'doctor:logout' %}"><span ></span> 登出</a></li>
      	<li id="login"><a href="{% url 'doctor:login' %}"><span ></span> 登陆</a></li>
        <li id="user">
          {% block user %}
          {% endblock %}
        </li>
      </ul>
    </div>
  </div>
</nav>

{% block patient_form %}
{% endblock %}
{% block register_form %}
{% endblock %}

{% block medicine_form %}
{{ message }}
{% endblock %}

mysite/doctor/templates/polls/login.html
{% extends 'polls/index.html' %}

{% block patient_form %}
<p>您还没有登陆，请先登录</p>
<p>或者您账号的权限不足，请使用更高权限的账号</p>
<form action="{% url 'doctor:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="登录" />
</form>
{% endblock %}

mysite/doctor/templates/polls/m.html
{% extends 'polls/index.html' %}

{% block patient_form %}

<p>登录成功</p>
{% endblock %}

mysite/doctor/templates/polls/message.html
{% extends 'polls/index.html' %}

{% block patient_form %}

<p>修改成功</p>
{% endblock %}

mysite/doctor/templates/polls/no_permission.html
{% extends 'polls/index.html' %}

{% block patient_form %}

<p>你没有访问权限</p>
{% endblock %}

mysite/doctor/templates/polls/p_num.html
{% extends 'polls/index.html' %}

{% block patient_form %}

<h3>给出需要检索的病人编号</h3>
<form action="http://localhost:8000/doctor/patient_num/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="查询此病人" />
</form>
{% endblock %}

mysite/doctor/templates/polls/patient.html
{% extends 'polls/index.html' %}


{% block patient_form %}

<div class="row">
    <div class="col-sm-3"></div>
  <div class="col-sm-6">

    <div class="container">
  <h2>病人信息</h2>
  <table class="table">
    <thead>
      <tr>
        <th>姓名</th>
        <th>病人编号</th>
        <th>性别</th>
      </tr>
    </thead>
    <tbody>
      {% for patient in all_patients %}
      <tr>
        <td>{{ patient.p_name }} </td>
        <td>{{ patient.p_number }}</td>
        <td>{{ patient.p_sex }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>






      <center>
          <div class="btn-group">
  <button type="button" class="btn btn-primary btn-lg"  onclick='location.href="http://localhost:8000/doctor/patient_log"'>录入</button>
  <button type="button" class="btn btn-primary btn-lg" onclick='location.href="http://localhost:8000/doctor/patient_edit"'>编辑</button>
  <button type="button" class="btn btn-primary btn-lg" onclick='location.href="http://localhost:8000/doctor/patient_search"'>查询</button>
    </div>
      </center>

  </div>
  <div class="col-sm-3"></div>
</div>

{% endblock %}

mysite/doctor/templates/polls/patient_display.html
{% extends 'polls/index.html' %}

{% block patient_form %}





  <table class="table">
    <thead>
      <tr>
        <th>姓名</th>
        <th>病人编号</th>
        <th>性别</th>
          <th>电话号码</th>
          <th>年龄</th>
          <th>住址</th>
          <th>婚姻情况</th>
          <th>证件号码</th>
          <th>以往病历</th>
      </tr>
    </thead>
    <tbody>
      <tr>
          <td>{{ patient.p_name }} </td>
          <td>{{ patient.p_number }}</td>
          <td>{{ patient.p_sex }}</td>
          <td>{{ patient.p_tel_number }}</td>
          <td>{{ patient.p_age}}</td>
          <td>{{ patient.p_address}}</td>
          <td>{{ patient.p_marriage}}</td>
          <td>{{ patient.p_id_num }}</td>
          <td><a href="http://localhost:8000/doctor/diag_record/{{ patient.p_number }}/">点击查看</a></td>


      </tr>
    </tbody>
  </table>
{% endblock %}

mysite/doctor/templates/polls/patient_edit.html
{% extends 'polls/index.html' %}


{% block patient_form %}

<h3>病人信息修改</h3>
<form action="http://localhost:8000/doctor/patient_num/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="修改此病人的信息" />
</form>

{% endblock %}

mysite/doctor/templates/polls/patient_log.html
{% extends 'polls/index.html' %}

{% block patient_form %}
<h3>病人信息录入</h3>
<form action="http://localhost:8000/doctor/patient_log/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="添加" />
</form>

{% if  isok  %}
    <p>添加成功！您可以继续添加</p>
{% endif %}
{% endblock %}

mysite/doctor/templates/polls/patient_num.html
{% extends 'polls/index.html' %}

{% block patient_form %}
<h3>病人信息修改</h3>
<form action="http://localhost:8000/doctor/patient_edit/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="修改此病人的信息" />
</form>

{% endblock %}

mysite/doctor/templates/polls/patient_search.html
{% extends 'polls/index.html' %}

{% block patient_form %}

<h3>给出需要检索的病人编号</h3>
<form action="http://localhost:8000/doctor/patient_search/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="查询此病人" />
</form>
<button type="button" class="btn btn-primary btn-lg" onclick='location.href="http://localhost:8000/doctor/patient_search_day"'>查询今日就诊的病人</button>

{% endblock %}

mysite/doctor/templates/polls/patient_search_day.html
{% extends 'polls/index.html' %}


{% block patient_form %}

<div class="row">
    <div class="col-sm-3"></div>
  <div class="col-sm-6">

    <div class="container">
  <h2>病人信息</h2>
  <table class="table">
    <thead>
      <tr>
        <th>姓名</th>
        <th>病人编号</th>
        <th>性别</th>
      </tr>
    </thead>
    <tbody>
      {% for patient in all_person %}
      <tr>
        <td>{{ patient.p_name }} </td>
        <td>{{ patient.p_number }}</td>
        <td>{{ patient.p_sex }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
        <p>总人数：{{ length }}</p>
</div>
  </div>
  <div class="col-sm-3"></div>
</div>

{% endblock %}